In [1]:
import pandas as pd
import numpy as np

In [2]:
USERS_PATH = "cresci-2015/TFP/users.csv"
TWEETS_PATH = "cresci-2015/TFP/tweets.csv"
PROCESSED_USERS_PATH = "cresci-2015/TFP/users_processed.csv"

In [3]:
pd.set_option('display.max_columns', 500)

users_df = pd.read_csv(USERS_PATH)
tweets_df = pd.read_csv(TWEETS_PATH)

In [4]:
users_df = users_df[users_df["id"].isin(tweets_df["user_id"].unique())]
users_df.head(n=10)

,id,name,screen_name,statuses_count,followers_count,friends_count,favourites_count,listed_count,created_at,url,lang,time_zone,location,default_profile,default_profile_image,geo_enabled,profile_image_url,profile_banner_url,profile_use_background_image,profile_background_image_url_https,profile_text_color,profile_image_url_https,profile_sidebar_border_color,profile_background_tile,profile_sidebar_fill_color,profile_background_image_url,profile_background_color,profile_link_color,utc_offset,protected,verified,description,updated,dataset
0,24503,Roberto Bonanzinga,Bonanzinga,4340,5055,1466,267,256,Mon Nov 27 06:55:12 +0000 2006,http://t.co/32VHs0bxbY,en,Pacific Time (US & Canada),Between Europe and the US,NaN,NaN,1.0,http://a0.twimg.com/profile_images/15225602/Ro...,NaN,1.0,https://si0.twimg.com/profile_background_image...,3E4415,https://si0.twimg.com/profile_images/15225602/...,829D5E,1.0,99CC33,http://a0.twimg.com/profile_background_images/...,352726,D02B55,-28800.0,NaN,NaN,Partner at Balderton Capital (formerly Benchma...,2015-02-14 11:32:57,TFP
1,22903,effeffe,effeffe,164,132,194,12,4,Sun Nov 26 15:19:32 +0000 2006,http://t.co/CX7EHdk9DJ,it,Rome,"Napoli, Italy",NaN,NaN,NaN,http://a0.twimg.com/profile_images/3653487844/...,https://pbs.twimg.com/profile_banners/22903/13...,1.0,https://si0.twimg.com/images/themes/theme14/bg...,333333,https://si0.twimg.com/profile_images/365348784...,EEEEEE,1.0,EFEFEF,http://a0.twimg.com/images/themes/theme14/bg.gif,131516,009999,3600.0,NaN,NaN,L'uomo ha creato dio a sua immagine e somiglia...,2015-02-14 11:32:57,TFP
2,382393,Ciro Cattuto,ciro,1070,1154,832,871,92,Sun Dec 31 02:03:17 +0000 2006,http://t.co/26dNjSYe5Q,en,Rome,"Torino, Piedmont",NaN,NaN,1.0,http://a0.twimg.com/profile_images/56071111/ci...,NaN,1.0,https://si0.twimg.com/images/themes/theme2/bg.gif,663B12,https://si0.twimg.com/profile_images/56071111/...,C6E2EE,NaN,DAECF4,http://a0.twimg.com/images/themes/theme2/bg.gif,C6E2EE,1F98C7,3600.0,NaN,NaN,Research Director at ISI Foundation. Data scie...,2015-02-14 11:32:57,TFP
3,286543,Alessio Bragadini,abragad,6892,930,535,478,28,Wed Dec 27 14:55:17 +0000 2006,http://t.co/xoOdZi9jic,en,Rome,"Milan, Italy",NaN,NaN,1.0,http://a0.twimg.com/profile_images/1398384510/...,https://twimg0-a.akamaihd.net/profile_banners/...,1.0,https://twimg0-a.akamaihd.net/profile_backgrou...,000000,https://twimg0-a.akamaihd.net/profile_images/1...,87BC44,NaN,E0FF92,http://a0.twimg.com/profile_background_images/...,9AE4E8,0000FF,3600.0,NaN,NaN,Web and social media developer from Italy,2015-02-14 11:32:57,TFP
4,438023,fullcaffeine,fullcaffeine,2885,173,444,41,2,Tue Jan 02 09:01:50 +0000 2007,http://www.fullcaffeine.com,it,Rome,Bologna,NaN,NaN,1.0,http://a0.twimg.com/profile_images/17830372/me...,NaN,1.0,https://si0.twimg.com/images/themes/theme14/bg...,333333,https://si0.twimg.com/profile_images/17830372/...,EEEEEE,1.0,EFEFEF,http://a0.twimg.com/images/themes/theme14/bg.gif,131516,009999,3600.0,NaN,NaN,NaN,2015-02-14 11:32:57,TFP
5,586003,Maurizio Tesconi,myself2048,216,97,234,2,0,Fri Jan 05 16:20:42 +0000 2007,http://maurizio.tesconi.it/,en,Rome,Pisa,NaN,NaN,1.0,http://a0.twimg.com/profile_images/2964961743/...,https://si0.twimg.com/profile_banners/586003/1...,1.0,https://si0.twimg.com/images/themes/theme1/bg.png,000000,https://si0.twimg.com/profile_images/296496174...,87BC44,NaN,E0FF92,http://a0.twimg.com/images/themes/theme1/bg.png,9AE4E8,0000FF,3600.0,NaN,NaN,CNR Researcher. Web developer. Social media ge...,2015-02-14 11:32:57,TFP
6,628563,Massimo Moretti,MaxMoretti,505,154,314,0,3,Fri Jan 12 11:06:17 +0000 2007,http://www.moretti.rm.it/,it,Rome,Roma,NaN,NaN,1.0,http://a0.twimg.com/profile_images/1667873316/...,https://si0.twimg.com/profile_banners/628563/1...,1.0,https://si0.twimg.com/profile_background_image...,333333,https://si0.twimg.com/profile_images/166787331...,C0DEED,NaN,DDEEF6,http://a0.twimg.com/profile_background_images/...,C0DEED,0084B4,3600.0,NaN,NaN,The truth is out there!,2015-02-14 11:32:57,TFP
7,769985,Pasquale Popolizio,pasquale,1897,1100,975,68,39,Tue Feb 13 16:09:05 +0000 2007,http://digitalstrategicplanner.info/,en,Rome,Web,NaN,NaN,1.0,http://a0.twimg.com/profile_images/2181744546/...,NaN,1.0,https://si0.twimg.com/images/themes/theme1/bg.png,000000,https://si0.twimg.com/profile_images/218174454...,FFFFFF,NaN,E0FF92,http://a0.twimg.com/images/themes/theme1/bg.png,9AE4E8,0000FF,3600.0,NaN,NaN,Digital strategic plannerhttp://digitalstrateg...,2015-02-14 11:32:57,TFP
8,2007021,Roberto Ciacci,robertociacci,3052,2254,2196,318,98,Fri Mar 23 12:43:59 +0000 2007,http://www.linkedin.com/in/robertociacci,it,Rome,"44.479507,11.277889",NaN,NaN,NaN,http://a0.twimg.com/profile_images/2258443729/...,NaN,1.0,https://si0.twimg.com/profile_background_image...,666666,https://si0.twimg.com/profile_images/225844372...,000000,1.0,E8EBF0,http://a0.twimg.com/profile_background_images/...,676A6F,FF0000,3600.0,NaN,NaN,Digital Marketing Manager @renowned brand. Que...,2015-02-14 11:32:57,TFP
9,2731681,Francesco,Surfcanarias,313,31,55,1,1,Wed Mar 28 22:02:12 +0000 2007,http://windsurfparadise.blogspot.com,it,Rome,"Bilbao, Spain",NaN,NaN,1.0,http://a0.twimg.com/profile_images/19211452/ev...,NaN,NaN,https://si0.twimg.com/profile_background_image...,000000,https://si0.twimg.com/profile_images/19211452/...,87BC44,NaN,E0FF92,http://a0.twimg.com/profile_background_images/...,9AE4E8,0000FF,3600.0,NaN,NaN,"Telecom Engineer, eMBA, social networker and k...",2015-02-14 11:32:57,TFP

In [5]:
tweets_df.head(n=10)

,created_at,id,text,source,user_id,truncated,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,retweeted_status_id,geo,place,retweet_count,reply_count,favorite_count,num_hashtags,num_urls,num_mentions,timestamp
0,Fri Dec 21 14:02:36 +0000 2012,282123910303080448,@TheFakeProject cerca followers reali!!! #ImNo...,web,22903,NaN,0,987007950,TheFakeProject,NaN,NaN,NaN,0,0.0,0.0,1,1,1,2012-12-21 15:02:36
1,Wed Dec 05 05:59:43 +0000 2012,276204184393641984,RT @laperniconi: Cosa ci metteremo quest'anno ...,"<a href=""http://twitter.com/#!/download/ipad"" ...",22903,NaN,0,0,NaN,NaN,NaN,NaN,18,0.0,0.0,1,0,3,2012-12-05 06:59:43
2,Wed Dec 05 05:55:01 +0000 2012,276203000333217792,RT @wontcallyouback: #faiunadomandaalpapa ha m...,"<a href=""http://twitter.com/#!/download/ipad"" ...",22903,NaN,0,0,NaN,NaN,NaN,NaN,686,0.0,0.0,1,0,1,2012-12-05 06:55:01
3,Thu Sep 20 15:25:38 +0000 2012,248805120802959362,RT @nausea_17: I tifosi del Napoli si picchian...,web,22903,NaN,0,0,NaN,NaN,NaN,NaN,1,0.0,0.0,0,0,1,2012-09-20 17:25:38
4,Sat Sep 08 14:28:10 +0000 2012,244442004661096448,@ioeilmiopc buonanotte a te che mi apri un mon...,"<a href=""http://twitter.com/#!/download/ipad"" ...",22903,NaN,244441040575143936,11154952,ioeilmiopc,NaN,NaN,NaN,0,0.0,1.0,0,0,1,2012-09-08 16:28:10
5,Tue Jul 10 21:15:39 +0000 2012,222801279339077633,“@nataliacavalli: @LeTwittine nel caso ti avvi...,"<a href=""http://twitter.com/#!/download/ipad"" ...",22903,NaN,0,0,NaN,NaN,NaN,NaN,0,1.0,0.0,0,0,2,2012-07-10 23:15:39
6,Mon Jul 09 04:31:24 +0000 2012,222186164419969024,@jessicaalba You'll be in Italy? happy holidays!,"<a href=""http://twitter.com/#!/download/ipad"" ...",22903,NaN,222160589106061312,92367751,jessicaalba,NaN,NaN,NaN,0,0.0,0.0,0,0,1,2012-07-09 06:31:24
7,Sun Jul 08 16:39:24 +0000 2012,222006983191044096,"@PakoRosato Hehehe, infatti velatamente citavo :)","<a href=""http://twitter.com/#!/download/ipad"" ...",22903,NaN,222006828236677120,435055772,PakoRosato,NaN,NaN,NaN,0,0.0,0.0,0,0,1,2012-07-08 18:39:24
8,Sun Jul 08 16:33:16 +0000 2012,222005439120941057,"@PakoRosato @LeTwittine ""amici miei"", che poes...","<a href=""http://twitter.com/#!/download/ipad"" ...",22903,NaN,221993145561382912,435055772,PakoRosato,NaN,NaN,NaN,0,1.0,0.0,0,0,2,2012-07-08 18:33:16
9,Thu Jun 21 11:08:15 +0000 2012,215763051008372737,Conseguenze di Scipione... http://t.co/FUgkYuqw,"<a href=""http://twitter.com/download/iphone"" r...",22903,NaN,0,0,NaN,NaN,NaN,NaN,0,0.0,0.0,0,0,0,2012-06-21 13:08:15

In [6]:
users = users_df.loc[:, ["id", "verified", "followers_count", "favourites_count", "friends_count"]]
users["friend_follower_ratio"] = users["friends_count"] / users["followers_count"]
users.reset_index(drop=True, inplace=True)
users.shape

(465, 6)

In [7]:
users.head(n=10)

,id,verified,followers_count,favourites_count,friends_count,friend_follower_ratio
0,24503,NaN,5055,267,1466,0.290010
1,22903,NaN,132,12,194,1.469697
2,382393,NaN,1154,871,832,0.720971
3,286543,NaN,930,478,535,0.575269
4,438023,NaN,173,41,444,2.566474
5,586003,NaN,97,2,234,2.412371
6,628563,NaN,154,0,314,2.038961
7,769985,NaN,1100,68,975,0.886364
8,2007021,NaN,2254,318,2196,0.974268
9,2731681,NaN,31,1,55,1.774194

In [8]:
users["mentions"] = tweets_df["num_mentions"].groupby(tweets_df["user_id"]).mean().reset_index(drop=True)
users["hashtags"] = tweets_df["num_hashtags"].groupby(tweets_df["user_id"]).mean().reset_index(drop=True)
users["urls"] = tweets_df["num_urls"].groupby(tweets_df["user_id"]).mean().reset_index(drop=True)
users["retweets"] = tweets_df["retweet_count"].groupby(tweets_df["user_id"]).mean().reset_index(drop=True)
users["favorites"] = tweets_df["favorite_count"].groupby(tweets_df["user_id"]).mean().reset_index(drop=True)

In [9]:
users.head(n=10)

,id,verified,followers_count,favourites_count,friends_count,friend_follower_ratio,mentions,hashtags,urls,retweets,favorites
0,24503,NaN,5055,267,1466,0.290010,0.701220,0.170732,0.048780,7.493902,0.030488
1,22903,NaN,132,12,194,1.469697,0.901161,0.185500,0.279524,1.885868,0.157976
2,382393,NaN,1154,871,832,0.720971,0.643067,0.306110,0.356345,103.532609,0.163317
3,286543,NaN,930,478,535,0.575269,0.845650,0.559401,0.416277,9.486436,0.441534
4,438023,NaN,173,41,444,2.566474,0.095700,0.041262,0.140777,1.325243,0.025000
5,586003,NaN,97,2,234,2.412371,1.165049,0.776699,0.422330,62.893204,0.065327
6,628563,NaN,154,0,314,2.038961,0.176707,0.102410,0.576305,4.158635,0.000000
7,769985,NaN,1100,68,975,0.886364,0.554140,0.559448,0.223461,1.551486,0.239796
8,2007021,NaN,2254,318,2196,0.974268,0.724490,0.441080,0.159315,10.544766,0.065327
9,2731681,NaN,31,1,55,1.774194,0.321429,0.272727,0.782468,3.337662,0.005000

In [10]:
for index, uid in enumerate(users["id"]):
    user_tweets = tweets_df[tweets_df["user_id"] == uid]
    unique_places = user_tweets["place"].value_counts()[user_tweets["place"].value_counts() == 1].shape[0]
    users.loc[index, "unique_places"] = unique_places

In [11]:
users.head(n=10)

,id,verified,followers_count,favourites_count,friends_count,friend_follower_ratio,mentions,hashtags,urls,retweets,favorites,unique_places
0,24503,NaN,5055,267,1466,0.290010,0.701220,0.170732,0.048780,7.493902,0.030488,96.0
1,22903,NaN,132,12,194,1.469697,0.901161,0.185500,0.279524,1.885868,0.157976,0.0
2,382393,NaN,1154,871,832,0.720971,0.643067,0.306110,0.356345,103.532609,0.163317,5.0
3,286543,NaN,930,478,535,0.575269,0.845650,0.559401,0.416277,9.486436,0.441534,44.0
4,438023,NaN,173,41,444,2.566474,0.095700,0.041262,0.140777,1.325243,0.025000,17.0
5,586003,NaN,97,2,234,2.412371,1.165049,0.776699,0.422330,62.893204,0.065327,1.0
6,628563,NaN,154,0,314,2.038961,0.176707,0.102410,0.576305,4.158635,0.000000,5.0
7,769985,NaN,1100,68,975,0.886364,0.554140,0.559448,0.223461,1.551486,0.239796,5.0
8,2007021,NaN,2254,318,2196,0.974268,0.724490,0.441080,0.159315,10.544766,0.065327,6.0
9,2731681,NaN,31,1,55,1.774194,0.321429,0.272727,0.782468,3.337662,0.005000,16.0

In [12]:
for index, uid in enumerate(users["id"]):
    tweets_hour = []
    user_tweets = tweets_df[tweets_df["user_id"] == uid].sort_values(by="timestamp", ascending=False)
    user_tweets.reset_index(inplace=True, drop=True)
    S = pd.to_datetime(user_tweets["timestamp"])
    for key, values in user_tweets.groupby([(S - S[0]).astype("timedelta64[h]")]):
        tweets_hour.append(len(values))
        
    tweets_hour = np.array(tweets_hour)
    users.loc[index, "tweet_rate_variance"] = np.var(tweets_hour)

In [13]:
users.head(n=10)

,id,verified,followers_count,favourites_count,friends_count,friend_follower_ratio,mentions,hashtags,urls,retweets,favorites,unique_places,tweet_rate_variance
0,24503,NaN,5055,267,1466,0.290010,0.701220,0.170732,0.048780,7.493902,0.030488,96.0,0.772762
1,22903,NaN,132,12,194,1.469697,0.901161,0.185500,0.279524,1.885868,0.157976,0.0,0.263310
2,382393,NaN,1154,871,832,0.720971,0.643067,0.306110,0.356345,103.532609,0.163317,5.0,0.173459
3,286543,NaN,930,478,535,0.575269,0.845650,0.559401,0.416277,9.486436,0.441534,44.0,0.436569
4,438023,NaN,173,41,444,2.566474,0.095700,0.041262,0.140777,1.325243,0.025000,17.0,2.453432
5,586003,NaN,97,2,234,2.412371,1.165049,0.776699,0.422330,62.893204,0.065327,1.0,0.250852
6,628563,NaN,154,0,314,2.038961,0.176707,0.102410,0.576305,4.158635,0.000000,5.0,0.743600
7,769985,NaN,1100,68,975,0.886364,0.554140,0.559448,0.223461,1.551486,0.239796,5.0,7.413680
8,2007021,NaN,2254,318,2196,0.974268,0.724490,0.441080,0.159315,10.544766,0.065327,6.0,2.304642
9,2731681,NaN,31,1,55,1.774194,0.321429,0.272727,0.782468,3.337662,0.005000,16.0,0.087603

In [14]:
users.to_csv(PROCESSED_USERS_PATH)